filters:
  - label: enhancement
    regexs:
      - /feat/i
      - /refactor/
    events: [issues, pull_request]
    targets: [title, comment]
  - label: bug
    regexs:
      - /\bfix\b|bug/
    targets: [title]
  - label: documentation
    regexs:
      - /docs/
    events: [pull_request]
